### ISSUE TITLE
LinePrinterException: LinePrintService is not available

### ISSUE THREAD

**Issue by basith0304** [hjgode/android-stuff#1]
I did Everything fine . even i have check Mac Address . But its throwing Error like

"`LinePrinterException: LinePrintService is not available`"

**Comment by hjgode** [comment]
Are you using an Intermec CN51 running Android? The LinePrinter stuff will not work on non-Intermec decices. In the meantime I prefer to use Bluetooth socket and no Intermec related or depending stuff.

**Comment by basith0304** [comment]
yes . i have already tested it working with Bluetooth socket .
i don't think so ,we can print image (company logo ) and stylish text like bold underline like that.

thanks ,basith

Get Outlook for iOS

```
    _____________________________
```

**Comment by hjgode** [comment]
How to print images and change fonts etc. depends on the printing language set in the printer. The easiest one will if set to fingerprint. Then you can define and save a layout in the printer, upload a PCX with the logo being used in the layout and then just send the variable data (example [here](https://github.com/hjgode/pricemarkdown))
