### ISSUE TITLE
Arabic Text Problem

### ISSUE THREAD

**Issue by Elsobkey** [hjgode/android-stuff#2]
Thank you for your effort,
Can you  help me t find a way to print arabic text?
Please help me

**Comment by hjgode** [comment]
To print arabic you need a printer with a full unicode font installed. Some TrueType fonts do not have all code points. If printer supports unicode and you send native printer commands, there should be no problem.

**Comment by Elsobkey** [comment]
Can you help me to do this?

**Comment by hjgode** [comment]
Hello Elsobkey

this is not the right place to ask for such help. Please post your question at stackoverflow.com and add as much details (device, OS, printer model etc.). You may also email the details to my blog at http://www.hjgode.de/wp/2014/12/18/android-development-btprint4-prints-demos-and-files-to-bluetooth-receipt-and-label-printers/.

thanks

Josef
